server.port=8080
spring.application.name=weather-backend-application

spring.main.allow-bean-definition-overriding=true
spring.cache.type=caffeine
logging.level.org.springframework.web=DEBUG

api_key=7907c436d29581bf9f5daf7b2517fe5a
